### ISSUE TITLE
one click installer..  cuda not working now.. was working previously 

### ISSUE THREAD

**Issue by XeonG** [oobabooga/one-click-installers#80]
fyi this was working fine before 

(C:\Projects\AI\one-click-installers\installer_files\env) C:\Projects\AI\one-click-installers>python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 2.0.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect

**Comment by jllllll** [comment]
This is a recurring issue with Pytorch's Conda packages. It has been happening since the first versions of the installer with no clear cause. It doesn't happen for everyone and has only ever happened to me once. Temporary fix is to run `cmd_windows.bat` and enter this command:
```
python -m pip install torch==2.0.1+cu117 --force-reinstall --no-deps --index-url https://download.pytorch.org/whl/cu117
```
A possible, more permanent fix might be to change [line 86](https://github.com/oobabooga/one-click-installers/blob/main/webui.py#L86) of `webui.py` to:
```python
run_cmd('conda install -y -k cuda-toolkit ninja git -c nvidia/label/cuda-11.7.0 -c nvidia && python -m pip install torch==2.0.1+cu117 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117', assert_success=True, environment=True)
```
That will cause Pytorch to be installed through pip rather than Conda. There have been other reliability concerns with the Conda package as well, even when it is installed correctly. So, we may end up needing to do this anyway.
